# Generated by Django 5.0.7 on 2024-07-19 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='director',
            new_name='job',
        ),
    ]
