# Generated by Django 5.0.7 on 2024-07-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_director_team_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='job',
            new_name='direktor',
        ),
    ]
